# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=200)),
                ('arabic_title', models.CharField(max_length=200)),
                ('german_title', models.CharField(max_length=200)),
                ('english_text', models.TextField()),
                ('arabic_text', models.TextField()),
                ('german_text', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Title')),
            ],
        ),
    ]
