# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
